# SPDX-FileCopyrightText: 2022 Pipeline Helper Contributors
#
# SPDX-License-Identifier: EUPL-1.2

image: docker.io/library/maven:3-eclipse-temurin-17

stages:
  - format
  - test
  - lint

variables:
  JACOCO_CSV_LOCATION: "$CI_PROJECT_DIR/target/site/jacoco/jacoco.csv"
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version

cache: &global-cache
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .m2/repository

spotless:
  stage: format
  script:
    - mvn $MAVEN_CLI_OPTS spotless:check
  cache:
    <<: *global-cache
  allow_failure: true

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean verify
    - sh ./scripts/coverage.sh $JACOCO_CSV_LOCATION
  cache:
    <<: *global-cache
  coverage: '/Instruction Coverage: \d+.\d+ %/'
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml
    expire_in: 1 week

checkstyle:
  stage: lint
  script:
    - mvn $MAVEN_CLI_OPTS checkstyle:checkstyle
    - cat target/checkstyle-result.xml | ./scripts/checkstyle_report.sh > checkstyle-report.json
  cache:
    <<: *global-cache
  artifacts:
    when: always
    reports:
      codequality:
        - checkstyle-report.json

reuse:
  stage: lint
  image:
    name: docker.io/fsfe/reuse
    entrypoint: [""]
  script:
    - reuse lint
